name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22


      - name: Install dependencies
        run: npm install


      - name: Install Capacitor Android
        run: npm install @capacitor/android


      - name: Install TypeScript
        run: npm install -D typescript


      - name: Add Android platform
        run: npx cap add android


      - name: Sync Capacitor
        run: npx cap sync android


      - name: Generate Android App Icon
        run: |
          npm install --save-dev @capacitor/assets
          npx @capacitor/assets generate --android \
            --iconBackgroundColor '#FFFFFF' \
            --iconBackgroundColorDark '#FFFFFF'


      - name: Sync Capacitor after generating assets
        run: npx cap sync android


      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21


      - name: Build Release APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleRelease


      - name: Rename APK
        run: |
          mkdir -p release
          cp android/app/build/outputs/apk/release/app-release.apk \
             release/Diwan-Alqabila-release.apk


      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: diwan-alqabila-release-apk
          path: release/Diwan-Alqabila-release.apk
          if-no-files-found: error
